print("Vital Signs Details\n")
PR = input("Enter Pulse Rate : ")
BP = input("Enter Blood Pressue : ")
OX = input("Enter Pulse Oximetry : ")
print(f"\n\nPulse Rate : {PR} \nBlood Pressue : {BP} \nPulse Oximetry : {OX}")